### PR TITLE
Adds ESM types

### LINKED ISSUE #54: does not work with ESM
Is there a way to use this package from an ESM project?

### PR DESCRIPTION
**Pull request by x3cion**
Fixes #54

### CODE REVIEW

**Comment by Zamiell** [comment]
@hoperyy Can you take a look at this PR? This is a blocker for people wanting to update to ESM.

**Comment by Zamiell** [comment]
@x3cion I tried this PR and I get this error:

image

I'm importing it like this:

```ts
import syncDirectory from "sync-directory";
```

Are you sure this PR is correct?

**Comment by x3cion** [comment]
@Zamiell I switched some things around when I checked it again, the default export wasn't right. I adapted the export to export the sync function, this is how it's supposed to be I think. 

Can you check again? If it still doesn't work, we could compare configs. 
image

**Comment by Zamiell** [comment]
@x3cion Seems to work now, thank you very much!
I've published the fork to npm at `@zamiell/sync-directory` for anyone who needs this in the meantime.

**Comment by hoperyy** [comment]
> @hoperyy Can you take a look at this PR? This is a blocker for people wanting to update to ESM.

Ahh Sorry for replying so late, really busy this days. Working on it!

**Comment by hoperyy** [comment]
v6.0.5 has been published https://www.npmjs.com/package/sync-directory/v/6.0.5 @x3cion @Zamiell @ritschwumm @G3z

**Comment by Zamiell** [comment]
Awesome, thank you hoperyy!

**Pull request merged**
